name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21-ea'
          distribution: 'temurin'
      - name: Run the Maven verify phase
        run: ./mvnw --batch-mode --update-snapshots verify
